# Generated by Django 4.0.6 on 2024-08-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='nom_organisme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
