# Generated by Django 4.0.6 on 2024-08-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_menu_nom_organisme'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_approuved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RestaurantSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.admins')),
            ],
            options={
                'db_table': 'restaurant_seats',
            },
        ),
    ]
