# Generated by Django 4.0.6 on 2024-08-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_menu_is_approuved_restaurantseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_menus', to='backend.admins'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
