# Generated by Django 4.0.6 on 2024-08-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_menu_approved_by_menu_is_declined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='is_approved',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='menu',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_menus', to='backend.admins'),
        ),
    ]
