# Generated by Django 5.0.3 on 2024-03-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_mail_sent_credentials', models.IntegerField(default=0)),
                ('accepted_conditions', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
