# Generated by Django 5.0.3 on 2024-03-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Clients',
        ),
    ]
