# Generated by Django 5.0.3 on 2024-03-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0002_rename_users_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
