# Generated by Django 5.0.3 on 2024-03-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0003_alter_clients_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clients',
            index=models.Index(fields=['password'], name='password_idx'),
        ),
    ]
