# Generated by Django 5.0.3 on 2024-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0005_admins_token_admins_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='email',
            new_name='adresse_mail',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='lastname',
        ),
        migrations.AddField(
            model_name='admins',
            name='is_verification_mail_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='nom_organisme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='admins',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admins',
            name='id_service',
            field=models.IntegerField(choices=[(0, 'super_admin'), (1, 'client'), (2, 'professionnel')]),
        ),
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
