# Generated by Django 4.0.6 on 2024-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0006_rename_email_admins_adresse_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='num_siret',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
