# Generated by Django 4.0.6 on 2024-05-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0007_admins_num_siret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='menu_images/')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='pfe.admins')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
