# Generated by Django 4.0.6 on 2024-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0010_alter_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='number_dispo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
