# Generated by Django 4.0.6 on 2024-06-28 13:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0011_menu_number_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
